#! /bin/bash

set -e

if [[ -f .env ]]; then
    export $(cat .env | grep -v "#" | xargs)
fi

NOTEBOOK=false

while getopts ":d:s:i:n" opt; do
    case ${opt} in
        d )
            DATA_DIR=$OPTARG
            ;;
        s )
            SOURCE_DIR=$OPTARG
            ;;
        i )
            DOCKER_IMAGE=$OPTARG
            ;;
        n )
            NOTEBOOK=true
            ;;
        \? )
            echo "Usage: start_docker [-s sourcedir] [-d datadir] [-i imagename] [-n]"
             ;;
        : )
            echo "$OPTARG requires an argument." 1>&2
            ;;
    esac
done

if [[ -z "${DATA_DIR}" ]]; then
    echo "Data directory must be specified with the DATA_DIR environment variable or with -d option."
    exit 1
fi

if [[ -z "${SOURCE_DIR}" ]]; then
    echo "Source directory must be specified with the SOURCE_DIR environment variable or with -s option."
    exit 1
fi

if [[ -z "${DOCKER_IMAGE}" ]]; then
    echo "Docker image must be specified with the DOCKER_IMAGE environment variable or with -i option."
    exit 1
fi

if [ "$NOTEBOOK" = true ] ; then
    docker run \
           -p 8888:8888 \
           --volume=$SOURCE_DIR:/home/bio/source \
           --volume=$DATA_DIR:/data \
           -it $DOCKER_IMAGE
else
    docker run \
           --entrypoint "bash" \
           -p 8888:8888 \
           --volume=$SOURCE_DIR:/home/bio/source \
           --volume=$DATA_DIR:/data \
           -it $DOCKER_IMAGE
fi
