patterns={
    'SEQ_REF_PRE':"TTCTTGACGAGTTCTTCTGA",
    'SEQ_REF_POST':"ACGCGTCTGGAACAATCAAC",
    'SEQ_FWD':"GC(?P<fwd_code>.......)GATATTGCTGAAGAGCTTG",
    'SEQ_REV':"TT(?P<rev_code>........)CAGAGGTTGATTGTTCCAGA"
}

#    SEQ_FWD_RC=CAAGCTCTTCAGCAATATC.......GC
#     SEQ_REV_RC=TCTGGAACAATCAACCTCTG........AA
#     SEQ_TEST=GTCTGTCTCAGTCACACACAGTGT
#     SEQ_PRE_POST=TTCTTGACGAGTTCTTCTGA(.+)ACGCGTCTGGAACAATCAAC
#     SEQ_POST_PRE=ACGCGTCTGGAACAATCAAC(.+)TTCTTGACGAGTTCTTCTGA
#     SEQ_PRERC_POSTRC=TCAGAAGAACTCGTCAAGAA(.+)GTTGATTGTTCCAGACGCGT
#     SEQ_POSTRC_PRERC=GTTGATTGTTCCAGACGCGT(.+)TCAGAAGAACTCGTCAAGAA
#     SEQ_FWD_REVRC=GC.......GATATTGCTGAAGAGCTTG(.+)TCTGGAACAATCAACCTCTG........AA
#     SEQ_FWDRC_REV=CAAGCTCTTCAGCAATATC.......GC(.+)TT........CAGAGGTTGATTGTTCCAGA
#     SEQ_REVRC_FWD=TCTGGAACAATCAACCTCTG........AA(.+)GC.......GATATTGCTGAAGAGCTTG
#     SEQ_REV_FWDRC=TT........CAGAGGTTGATTGTTCCAGA(.+)CAAGCTCTTCAGCAATATC.......GC
